### PR TITLE
fix: warning of useless components

### LINKED ISSUE #15: A warning is displayed when executing extractStyle() in Antd5
Hello.

Currently, when I proceeded with the implementation using the [official procedure to make Antd5 work with SSR](https://ant.design/docs/react/server-side-rendering#whole-export), the following warning is displayed when I execute extractStyle().

```
npm run dev

> predev
> ts-node --project ./tsconfig.node.json --esm ./scripts/genAntdCss.tsx

Warning: `children` of ResizeObserver is empty. Nothing is in observe.
Warning: [antd: BackTop] `BackTop` is deprecated. Please use `FloatButton.BackTop` instead.
Warning: [antd: Menu] `children` is deprecated. Please use `items` instead.
Warning: [antd: QRCode] need to receive `value` props
Warning: `children` of Tree is deprecated. Please use `treeData` instead.
```

Is there a way to solve this?

The environment and related code are as follows.

| library | version |
|--------|--------|
| React | 18.2.0 |
| ts-node | 10.9.2 | 
| antd | 5.14.2 | 
| @ant-design/static-style-extract | 1.0.2 | 

**genAntdCss.tsx**
```
import React from 'react';
import fs from 'fs';
import { extractStyle } from "@ant-design/static-style-extract";
import { ConfigProvider } from "antd";
import { customTheme } from "../app/theme.js";

const outputPath = "./public/antd.min.css";

// ↓ Code that displays the warning
const css = extractStyle((node) => (
  <ConfigProvider theme={{ token: customTheme }} >
    {node}
  </ConfigProvider>
));

fs.writeFileSync(outputPath, css);
```

### PR DESCRIPTION
**Pull request by zombieJ**
fix #15
close https://github.com/ant-design/ant-design/issues/50611

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -18,6 +19,26 @@ const blackList: string[] = [
...
+    </Affix>
+  ),
+  BackTop: () => <antd.FloatButton.BackTop />,
+  Dropdown: (Dropdown) => (
+    <Dropdown menu={{ items: [] }}>
+      <div />
+    </Dropdown>
+  ),
+  Menu: (Menu) => <Menu items={[]} />,
+  QRCode: (QRCode) => <QRCode value="https://ant.design" />,
```
Comment (yoyo837) [inline src/index.tsx:38]: @ant-design/static-style-extract 是只给antd site用的吗

Comment (zombieJ) [reply src/index.tsx:38]: 不是 site，是 antd 库。
